### ISSUE TITLE
HA 2023.8 - Animated scenes won't load and prevents HA from restarting

### ISSUE THREAD

**Issue by Snuffy2** [chazzu/hass-animated-scenes#24]
It was working fine in HA 2023.7.x. After updating to HA 2023.8 it is now giving the errors below and is preventing HA from restarting.

```
2023-08-02 22:21:37.715 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration animated_scenes which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-08-02 22:22:06.401 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration animated_scenes: Unable to import component: cannot import name 'RequiredParameterMissing' from 'homeassistant.exceptions' (/usr/src/homeassistant/homeassistant/exceptions.py)
File "/config/custom_components/animated_scenes/__init__.py", line 5, in <module>
File "/config/custom_components/animated_scenes/animations.py", line 32, in <module>
File "/config/custom_components/animated_scenes/__init__.py", line 5, in <module>
File "/config/custom_components/animated_scenes/animations.py", line 32, in <module>
File "/config/custom_components/animated_scenes/__init__.py", line 5, in <module>
File "/config/custom_components/animated_scenes/animations.py", line 32, in <module>
File "/config/custom_components/animated_scenes/__init__.py", line 5, in <module>
File "/config/custom_components/animated_scenes/animations.py", line 32, in <module>
File "/config/custom_components/animated_scenes/__init__.py", line 5, in <module>
File "/config/custom_components/animated_scenes/animations.py", line 32, in <module>
File "/config/custom_components/animated_scenes/__init__.py", line 5, in <module>
File "/config/custom_components/animated_scenes/animations.py", line 32, in <module>
File "/config/custom_components/animated_scenes/__init__.py", line 5, in <module>
File "/config/custom_components/animated_scenes/animations.py", line 32, in <module>
File "/config/custom_components/animated_scenes/__init__.py", line 5, in <module>
File "/config/custom_components/animated_scenes/animations.py", line 32, in <module>
File "/config/custom_components/animated_scenes/__init__.py", line 5, in <module>
File "/config/custom_components/animated_scenes/animations.py", line 32, in <module>
```

<img width="579" alt="2023-08-02_22-32-27 228" src="https://github.com/chazzu/hass-animated-scenes/assets/6526076/ff3f4209-8dac-4255-b679-446b7733e555">
<img width="570" alt="2023-08-02_22-32-37 352" src="https://github.com/chazzu/hass-animated-scenes/assets/6526076/30d47095-6415-43dc-9601-56c054473e6d">

.
I am using animated scenes from configuration.yaml
```yaml
- platform: animated_scenes
  name: "Front Porch Christmas Lights"
  ignore_off: False
  lights:
    - light.lifx_front_porch_light_bulb_1
    - light.lifx_front_porch_light_bulb_2
    - light.lifx_front_porch_light_bulb_3
  brightness: 255
  colors:
    - color_type: rgb_color
      color: [ 255, 0, 0 ]
    - color_type: rgb_color
      color: [ 240, 255, 254 ]
    - color_type: rgb_color
      color: [ 255, 98, 71 ]
    - color_type: rgb_color
      color: [ 255, 214, 0 ]
      weight: 5
    - color_type: rgb_color
      color: [ 125, 255, 0 ]
    - color_type: rgb_color
      color: [ 0, 255, 0 ]
  transition: [2, 6]
  change_frequency: [2, 6]
  change_amount: [1, 3]

- platform: animated_scenes
  name: Front Porch Patriotic Lights
  ignore_off: False
  lights:
    - light.lifx_front_porch_light_bulb_1
    - light.lifx_front_porch_light_bulb_2
    - light.lifx_front_porch_light_bulb_3
  brightness: 255
  colors:
    - color_type: rgb_color
      color: [ 255, 0, 0 ]
    - color_type: rgb_color
      color: [ 255, 255, 255 ]
    - color_type: rgb_color
      color: [ 0, 0, 255 ]
  transition: [2, 6]
  change_frequency: [2, 6]
  change_amount: all

- platform: animated_scenes
  name: Front Porch Valentines Lights
  ignore_off: False
  lights:
    - light.lifx_front_porch_light_bulb_1
    - light.lifx_front_porch_light_bulb_2
    - light.lifx_front_porch_light_bulb_3
  brightness: [100, 255]
  colors:
    - color_type: rgb_color
      color: [ 255, 0, 0 ]
    - color_type: rgb_color
      color: [ 255, 255, 255 ]
    - color_type: rgb_color
      color: [ 220, 20, 60 ]
    - color_type: rgb_color
      color: [ 255, 250, 250 ]
    - color_type: rgb_color
      color: [ 255, 20, 147 ]
    - color_type: rgb_color
      color: [ 255, 105, 180 ]
  transition: [2, 6]
  change_frequency: [2, 6]
  change_amount: [1, 3]

- platform: animated_scenes
  name: Front Porch NYE Lights
  ignore_off: False
  lights:
    - light.lifx_front_porch_light_bulb_1
    - light.lifx_front_porch_light_bulb_2
    - light.lifx_front_porch_light_bulb_3
  brightness: 255
  colors:
    - color_type: rgb_color
      color: [ 0,0,128 ]
    - color_type: rgb_color
      color: [ 64,224,208 ]
    - color_type: rgb_color
      color: [ 255, 255, 255 ]
    - color_type: rgb_color
      color: [ 192,192,192 ]
    - color_type: rgb_color
      color: [ 72,61,139 ]
    - color_type: rgb_color
      color: [ 0,0,255 ]
  transition: [2, 6]
  change_frequency: [2, 6]
  change_amount: all

- platform: animated_scenes
  name: Front Porch Easter Lights
  ignore_off: False
  lights:
    - light.lifx_front_porch_light_bulb_1
    - light.lifx_front_porch_light_bulb_2
    - light.lifx_front_porch_light_bulb_3
  brightness: [100, 255]
  colors:
    - color_type: rgb_color
      color: [ 255,255,0 ]
    - color_type: rgb_color
      color: [ 0,250,154 ]
    - color_type: rgb_color
      color: [ 64,224,208 ]
    - color_type: rgb_color
      color: [ 255,192,203 ]
    - color_type: rgb_color
      color: [ 255,250,205 ]
    - color_type: rgb_color
      color: [ 230,230,250 ]
  transition: [2, 6]
  change_frequency: [2, 6]
  change_amount: [1, 3]

- platform: animated_scenes
  name: "Front Porch Halloween Lights"
  ignore_off: False
  lights:
    - light.lifx_front_porch_light_bulb_1
    - light.lifx_front_porch_light_bulb_2
    - light.lifx_front_porch_light_bulb_3
  brightness: 255
  colors:
    - color_type: rgb_color
      color: [ 255, 195, 0 ]
    - color_type: rgb_color
      color: [ 255, 208, 114 ]
    - color_type: rgb_color
      color: [ 255, 169, 0 ]
    - color_type: rgb_color
      color: [ 255, 54, 6 ]
    - color_type: rgb_color
      color: [ 255, 140, 0 ]
  transition: [2, 6]
  change_frequency: [2, 6]
  change_amount: [1, 3]

- platform: animated_scenes
  name: As Bedroom Rainbow Sequence
  ignore_off: False
  restore: True
  restore_power: True
  animate_brightness: True
  animate_color: True
  lights:
    - light.localtuya_as_bedroom_light_bulb_1
    - light.localtuya_as_bedroom_light_bulb_2
    - light.localtuya_as_bedroom_light_bulb_3
    - light.localtuya_as_bedroom_light_bulb_4
  colors:
    - color_type: rgb_color
      color: [ 255, 0, 0 ]
    - color_type: rgb_color
      color: [ 255, 153, 0 ]
    - color_type: rgb_color
      color: [ 255, 255, 0 ]
    - color_type: rgb_color
      color: [ 0, 255, 0 ]
    - color_type: rgb_color
      color: [ 0, 0, 255 ]
    - color_type: rgb_color
      color: [ 0, 255, 255 ]
    - color_type: rgb_color
      color: [ 153, 51, 255 ]
    - color_type: rgb_color
      color: [ 255, 153, 255 ]
  transition: 1
  brightness: [128, 217]
  change_sequence: False
  change_frequency: [2, 5]
  change_amount: [1, 4]
```

**Comment by Snuffy2** [comment]
```
2023-08-02 22:39:18.632 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration animated_scenes: Unable to import component: cannot import name 'RequiredParameterMissing' from 'homeassistant.exceptions' (/usr/src/homeassistant/homeassistant/exceptions.py)
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/setup.py", line 215, in _async_setup_component
component = integration.get_component()
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/loader.py", line 813, in get_component
ComponentProtocol, importlib.import_module(self.pkg_path)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 940, in exec_module
File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
File "/config/custom_components/animated_scenes/__init__.py", line 5, in <module>
from .animations import Animations
File "/config/custom_components/animated_scenes/animations.py", line 32, in <module>
from homeassistant.exceptions import IntegrationError, RequiredParameterMissing
ImportError: cannot import name 'RequiredParameterMissing' from 'homeassistant.exceptions' (/usr/src/homeassistant/homeassistant/exceptions.py)
```

**Comment by nsheldon** [comment]
I’m experiencing this issue as well. Went from 2023.7.3 to 2023.8.1 and started seeing this error immediately after the update.

——
This error originated from a custom integration.

Logger: homeassistant.setup
Source: custom_components/animated_scenes/animations.py:32
Integration: animated_scenes (documentation, issues) 
First occurred: 12:12:03 PM (1 occurrences) 
Last logged: 12:12:03 PM

Setup failed for custom integration animated_scenes: Unable to import component: cannot import name 'RequiredParameterMissing' from 'homeassistant.exceptions' (/usr/src/homeassistant/homeassistant/exceptions.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 215, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 813, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/animated_scenes/__init__.py", line 5, in <module>
    from .animations import Animations
  File "/config/custom_components/animated_scenes/animations.py", line 32, in <module>
    from homeassistant.exceptions import IntegrationError, RequiredParameterMissing
ImportError: cannot import name 'RequiredParameterMissing' from 'homeassistant.exceptions' (/usr/src/homeassistant/homeassistant/exceptions.py)

**Comment by chazzu** [comment]
This should be resolved in release 1.0.4, just published. I confirmed on my end that Home Assistant 2023.8 works for me now, but please let me know if you run into any other issues.

**Comment by nsheldon** [comment]
It’s working great now. Thanks!
