### ISSUE TITLE
Failed to switch on after updating on 2024.1.6+ HA versions.

### ISSUE THREAD

**Issue by gvengivarr** [chazzu/hass-animated-scenes#36]
Hello. I got an issue with ~ Feb-March update of HA. When I try to switch on animated scenes switch (configured in HA conf file) the error is "Failed to call the service switch/turn_on. 'NoneType' object has no attribute 'cancel'.
I tried add this attribute by hand, but integration didn't run because it is "wrong config sample" etc.
![image](https://github.com/chazzu/hass-animated-scenes/assets/98362771/7604d7e6-4b8b-4448-8154-6df6d78e5a9b)
I revert my HA back to 2024.1.6 and animated scenes works again.
How can I have an updated HA and working scenes?
Thank you

**Comment by djahren** [comment]
I've had a very similar issue and I didn't notice when it stopped working but around 2024.1.6 seems correct. 

When turning on an animated scene I get:
`Failed to call service switch/turn_on. 'float' object cannot be interpreted as an integer`

And when I turn it back off I get the same message as above. 
`Failed to call service switch/turn_off. 'NoneType' object has no attribute 'cancel'`

**Comment by gvengivarr** [comment]
> Під час увімкнення анімованої сцени я отримую: `Failed to call service switch/turn_on. 'float' object cannot be interpreted as an integer`
When you write this, I remember that the first message was about 'float'

**Comment by chazzu** [comment]
Can you share your configuration?

**Comment by gvengivarr** [comment]
[configuration.txt](https://github.com/chazzu/hass-animated-scenes/files/14567558/configuration.txt)
Shure

> Can you share your configuration?

**Comment by chazzu** [comment]
@gvengivarr I copied your configuration into my development copy of Home Asssistant and could not reproduce the problem. There was a recent change published yesterday, v1.2.1, which solved a problem with floats. It may be that this is already solved. Can you update your integration and let me know?

**Comment by djahren** [comment]
The v1.2.1 update fixed the issue for me.

**Comment by gvengivarr** [comment]
> @gvengivarr I copied your configuration into my development copy of Home Asssistant and could not reproduce the problem. There was a recent change published yesterday, v1.2.1, which solved a problem with floats. It may be that this is already solved. Can you update your integration and let me know?

After updating HA to v2024.3.0 and animated_scenes to v1.2.1 at first I got some 'wrong config error", but after reloading again an issue was solved.
Thank you:)

**Comment by gvengivarr** [comment]
Hi. After some HA update still got similar errors. Again:(
Failed to call service switch/turn_off. 'NoneType' object has no attribute 'state'

**Comment by gvengivarr** [comment]
Hi. After some HA update still got similar errors. Again:(
Failed to call service switch/turn_off. 'NoneType' object has no attribute 'state'
